### ISSUE TITLE
KAG Editor - Cannot edit text

### ISSUE THREAD

**Issue by InochiPM** [begerard/KagEditor#1]
I'm stumped on how im supposed to edit the text in this .ks file as its just showing me the same thing my hex editor is showing me but at least i can edit in that.

**Comment by begerard** [comment]
The .KS file is just a text file. You can open it in your usual text editor (it can be Notepad++ or Word) no need for hex editor.

This app is more a convertor than an integrated edition software, as translators usually already have their preferred plateform. It is only here to handle the text format (JIS instead of ASCII/UTF8) and the KS tags.

Feel free to give me your use case if you want a detailed how to.
